version: "3.7"
services:
  gateway:
    container_name: gateway
    build: ./gateway
    environment:
      - DB_N=3
    ports:
      - "8080:8080"
    volumes:
      - ./gateway:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - db-0
      - db-1
      - db-2

  db-0:
    container_name: db-0
    build: ./db
    expose:
      - "8081"
    volumes:
      - ./db:/usr/src/app
      - /usr/src/app/node_modules

  db-1:
    container_name: db-1
    build: ./db
    expose:
      - "8081"
    volumes:
      - ./db:/usr/src/app
      - /usr/src/app/node_modules

  db-2:
    container_name: db-2
    build: ./db
    expose:
      - "8081"
    volumes:
      - ./db:/usr/src/app
      - /usr/src/app/node_modules
